### ISSUE TITLE
Nice Package...

### ISSUE THREAD

**Issue by mikeerickson** [spatie/laravel-tinker-tools#2]
Would sure be nice if stuff like this was added to the Tinker package by default so that it is already ready for me to use.   Granted, it only takes a couple minutes to install, but having it part of the core would sure be swell.

Thanks for the package nonetheless (where was it on the weekend when I was doing a slew of tinkering).

**Comment by freekmurze** [comment]
Thanks for the kind words on our work.

My thinking is that this package is maybe a bit too hacky to be added to Laravel itself.

But be my guest and open a PR at the Laravel organisation that adds this package (or the code contained in this package).

**Comment by mikeerickson** [comment]
@freekmurze Ya, I don't think I will waste my time creating a PR.  I know where it will land :-)

**Comment by inxilpro** [comment]
See https://github.com/laravel/tinker/pull/18

**Comment by freekmurze** [comment]
> My thinking is that this package is maybe a bit too hacky to be added to Laravel itself.

Guess I was wrong 😄 

Thanks @inxilpro for PR'ing the code of this package to Laravel. 👍  Really glad it got accepted.

**Comment by inxilpro** [comment]
Thanks for making it possible! Such a fantastic tool.
