### ISSUE TITLE
Laravel 5.2 support

### ISSUE THREAD

**Issue by sdbruder** [spatie/laravel-tinker-tools#4]
Ive implemented Laravel 5.2 support: the obstacle was the order swap of closure parameters on the collection->first() method, basically. 

Because of that now I call app()::VERSION to check for laravel version and now the test fail (because in the test environment we don't have access to the whole laravel environment).

So before submitting a Pull Request with it, I do accept suggestions on how to fix the tests first.

**Comment by sdbruder** [comment]
Ok, got around that: changed ->first() to ->search() because that didn't changed, working with Laravel 5.2-5.4.

Interested in the PR?

**Comment by freekmurze** [comment]
Thanks for the offer, but not interested in Laravel 5.2 compatibility. To me anything older than `5.4` is dead 😄

**Comment by sdbruder** [comment]
Sorry, Im curious: 
What do you do with your legacy code? 
You always update the Laravel framework or you never update?

**Comment by freekmurze** [comment]
Mostly if we touch a project in a significant way we'll upgrade it to the latest Laravel version.

If we for some reason can't upgrade the app and need one of our newer packages, we'll copy over the code of the package inside the app and make in compatible there. That rarely happens though.

**Comment by sdbruder** [comment]
Done a fork of it with laravel 5.2 support (heck, probably it can go lower than that, I didn't tested) in https://github.com/sdbruder/laravel-tinker-tools
