### ISSUE TITLE
Suggestion: autocomplete or allow select which class

### ISSUE THREAD

**Issue by mfn** [spatie/laravel-tinker-tools#5]
From the readme:
> Well, autoload_classmap.php is sorted alphabetically on the fully qualified namespace. So App\Models\NewsItem will be used and not Vendor\PackageName\NewsItem

I think to be really useful, it should allow the user to select which one. The first may not be correct one and then nothing is gained.

Autocomplete is probably a dream feature but maybe it's possible to show an option of classes to select one.

However I can easily imagine this is way too complex because it would have to happen right during the code-writing and not interrupt this, so .... just an idea `¯\_(ツ)_/¯`

**Comment by freekmurze** [comment]
I'm open for PRs that can customize / optimize the behaviour of this package.
