### ISSUE TITLE
Classname collisions... my approach

### ISSUE THREAD

**Issue by jszobody** [spatie/laravel-tinker-tools#6]
I took a stab at handling class name collisions, you can see it here:

https://gist.github.com/jszobody/b4eebc582b1840021e20794b672144b9

Note I modified this to be PHP 5.6 compatible (I know, I know. But I don't have a choice in one of my apps) so it's not exactly PR ready as-is.

If you like the approach other than the PHP version, I can submit a PR to your PHP 7 class.

**Comment by freekmurze** [comment]
Nice. If you PR that changes in a non-breaking, fully tested way, there's a good chance I'll pull it in.
