### ISSUE TITLE
Can't use short class from laravel-permission package

### ISSUE THREAD

**Issue by AmmarCodes** [spatie/laravel-tinker-tools#7]
Hi,

I'm having trouble when using the package with spatie/laravel-permission, I can't use `Role` short class name inside tinker after applying installation instructions for both packages.

## Steps to reproduce:
1. Fresh Laravel installation
2. `composer require spatie/laravel-permission`, then add the service provider to `config/app.php`
3. `composer require spatie/laravel-tinker-tools` and create the `.psysh.php` with the content in the readme.
4. `composer dump-autoload -o`
5. `php artisan tinker`
6. Add: `User::create(['name' =>'test', 'email' => 'test@test.com', 'password' => '123']);` <- This works.
7. Add: `Role::create(['name' => 'admin']);' <- This doesn't work. I get: `PHP Fatal error:  Class 'Role' not found in eval()'d code on line 1`

I'm on PHP 7.1.6 installed with homebrew.

**Comment by freekmurze** [comment]
Found the problem and fixed it in the newly tagged `v1.0.1`
